### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by kvndrsslr** [Jean-Tinland/simple-bar-lite#2]
Hey mate, I just found this and I am curious what prompted you to do this rewrite. I love simple-bar and have been previously contributing to it, however one thing that I find annoying is that its response times are really slow and that sometimes it randomly shows error because it got invalid data from `yabai -m query ...` (which I was never able to reproduce in the shell).
Is this rewrite fixing those things?

**Comment by Jean-Tinland** [comment]
Hi!

First thank you for your contributions, I'm glad you find the project interesting enough to be a part of it :)

There are indeed some issue like you said with simple-bar. I'm experiencing it myself but not a lot since my job provides me a high end mac book pro and I think the issue is more or less visible depending on the mac book model you have and its capacities.

I rewrote this simplified version of simple-bar principaly because It feels like simple-bar is not so simple anymore and it has grown a lot (which is a good thing since it seems to be usefull to more people this way). This increased range of functionnalities has made maintenance & bug fixing a bit more time consuming than I was expecting (as I need now to support some modules I haven't developped myself).

The goal of this lite version is to provide a bare version of simple-bar which is lighter (no more settings module for example) that works with a json config - I think most users are developper or at least tech profiles that don't mind having to edit some config files manually - and is extensible either by adding some custom widgets in config or by forking the project.

In the end I don't really know if this version is fixing the slow response time of some queries but it seems so as I'm using less heavy yabai queries.

Edit: typos
