### ISSUE TITLE
SpaceWidget is delayed when change desktop with touchpad

### ISSUE THREAD

**Issue by trungdt880** [Jean-Tinland/simple-bar-lite#4]
When I change the desktop by swiping the touchpad, the indicator of the current desktop is slow to respond. Anyway to fix this?
Many thanks

**Comment by Jean-Tinland** [comment]
Unfortunately I don't think performances can be improved as simple-bar is signal based: each time you switch space simple-bar is querying information from yabai about the new current space in order to display the active space and current application title. This operation can take times depending on the number of spaces and opened applications (+ the configuration of your computer).

**Comment by Jean-Tinland** [comment]
This issue has been resolved in `simple-bar` but not `simple-bar-lite`.

You can use [`simple-bar`](https://www.jeantinland.com/toolbox/simple-bar/) with [`simple-bar-server`](https://www.jeantinland.com/toolbox/simple-bar-server/) in order to signal more directly spaces & data widgets when you need it to be refreshed.
